add-regression-tests-for-role-user (patch 1 of 1)
'git apply --summary --stat --apply --verbose' output was:

Checking patch src/test/regress/expected/role.out...
Checking patch src/test/regress/parallel_schedule...
error: while searching for:
# ----------
# Another group of parallel tests
# ----------
test: privileges security_label collate matview

# ----------
# Another group of parallel tests

error: patch failed: src/test/regress/parallel_schedule:83
error: src/test/regress/parallel_schedule: patch does not apply
Checking patch src/test/regress/serial_schedule...
error: while searching for:
test: security_label
test: collate
test: matview
test: alter_generic
test: misc
test: psql

error: patch failed: src/test/regress/serial_schedule:96
error: src/test/regress/serial_schedule: patch does not apply
Checking patch src/test/regress/sql/role.sql...
/tmp/pg-quilter-postgres20130715-2-o38b21:346: new blank line at EOF.
+

For original context, see http://www.postgresql.org/message-id/CAEP4nAznaKyEcxMrrsQ8RBvDOAeAXE5=V2AsfM8JpLORuCGaPQ@mail.gmail.com