v9-4-row-level-security (patch 1 of 1)
'git apply --summary --stat --apply --verbose' output was:

/tmp/pg-quilter-postgres20130715-2-433zto:889: space before tab in indent.
 		 * row-level security policy
/tmp/pg-quilter-postgres20130715-2-433zto:2234: trailing whitespace.
 * would be given. Because the sub-query has security barrier flag,
/tmp/pg-quilter-postgres20130715-2-433zto:3523: trailing whitespace.
 did | cid | dlevel |      dauthor      |        dtitle
/tmp/pg-quilter-postgres20130715-2-433zto:3536: trailing whitespace.
 cid | did | dlevel |      dauthor      |        dtitle         |      cname
/tmp/pg-quilter-postgres20130715-2-433zto:3555: trailing whitespace.
 did | cid | dlevel |      dauthor      |        dtitle
Checking patch doc/src/sgml/catalogs.sgml...
Checking patch doc/src/sgml/ref/alter_table.sgml...
Checking patch doc/src/sgml/user-manag.sgml...
Checking patch src/backend/catalog/Makefile...
Checking patch src/backend/catalog/dependency.c...
Checking patch src/backend/catalog/heap.c...
Checking patch src/backend/catalog/objectaddress.c...
Checking patch src/backend/catalog/pg_rowsecurity.c...
Checking patch src/backend/commands/copy.c...
Checking patch src/backend/commands/event_trigger.c...
Checking patch src/backend/commands/tablecmds.c...
Checking patch src/backend/nodes/copyfuncs.c...
Checking patch src/backend/nodes/equalfuncs.c...
Checking patch src/backend/nodes/nodeFuncs.c...
Checking patch src/backend/nodes/outfuncs.c...
Checking patch src/backend/nodes/readfuncs.c...
Checking patch src/backend/optimizer/plan/planner.c...
Checking patch src/backend/optimizer/prep/preptlist.c...
Checking patch src/backend/optimizer/prep/prepunion.c...
Checking patch src/backend/optimizer/util/Makefile...
Checking patch src/backend/optimizer/util/rowsecurity.c...
Checking patch src/backend/parser/gram.y...
Checking patch src/backend/parser/parse_agg.c...
Checking patch src/backend/parser/parse_expr.c...
Checking patch src/backend/parser/parse_relation.c...
Checking patch src/backend/rewrite/rewriteHandler.c...
Checking patch src/backend/utils/adt/ri_triggers.c...
Checking patch src/backend/utils/cache/plancache.c...
Checking patch src/backend/utils/cache/relcache.c...
Checking patch src/bin/pg_dump/common.c...
Checking patch src/bin/pg_dump/pg_backup_archiver.c...
Checking patch src/bin/pg_dump/pg_dump.c...
Checking patch src/bin/pg_dump/pg_dump.h...
Checking patch src/bin/pg_dump/pg_dump_sort.c...
Checking patch src/bin/psql/describe.c...
Checking patch src/include/catalog/dependency.h...
Checking patch src/include/catalog/indexing.h...
Checking patch src/include/catalog/pg_class.h...
Checking patch src/include/catalog/pg_rowsecurity.h...
Checking patch src/include/miscadmin.h...
Checking patch src/include/nodes/execnodes.h...
Checking patch src/include/nodes/nodeFuncs.h...
Checking patch src/include/nodes/parsenodes.h...
Checking patch src/include/nodes/plannodes.h...
Checking patch src/include/nodes/relation.h...
Checking patch src/include/optimizer/rowsecurity.h...
Checking patch src/include/parser/parse_node.h...
Checking patch src/include/parser/parsetree.h...
Checking patch src/include/rewrite/rewriteHandler.h...
Checking patch src/include/utils/plancache.h...
Checking patch src/include/utils/rel.h...
Checking patch src/test/regress/expected/rowsecurity.out...
Checking patch src/test/regress/expected/sanity_check.out...
Checking patch src/test/regress/parallel_schedule...
error: while searching for:
# ----------
# Another group of parallel tests
# ----------
test: privileges security_label collate matview

# ----------
# Another group of parallel tests

error: patch failed: src/test/regress/parallel_schedule:83
error: src/test/regress/parallel_schedule: patch does not apply
Checking patch src/test/regress/serial_schedule...
Checking patch src/test/regress/sql/rowsecurity.sql...

For original context, see http://www.postgresql.org/message-id/CADyhKSXFzQBXQoNwiKdN9xxoVw7Zqz9gmF64Sry57QKduSFwSQ@mail.gmail.com