pgbench-patches (patch 1 of 1)
'git apply --summary --stat --apply --verbose' output was:

/tmp/pg-quilter-postgres20130714-2-1427gzp:10: trailing whitespace.
#define PTHREAD_FORK_EMULATION
/tmp/pg-quilter-postgres20130714-2-1427gzp:18: trailing whitespace.
int			progress = 0;       /* thread progress report every this seconds */
/tmp/pg-quilter-postgres20130714-2-1427gzp:19: trailing whitespace.
int         progress_nclients = 0; /* number of clients for progress report */
/tmp/pg-quilter-postgres20130714-2-1427gzp:27: trailing whitespace.
		   "  -P, --progress NUM       show thread progress report every NUM seconds\n"
/tmp/pg-quilter-postgres20130714-2-1427gzp:35: trailing whitespace.
		{"progress", required_argument, NULL, 'P'},
Checking patch contrib/pgbench/pgbench.c...
error: while searching for:
#include <pthread.h>
#else
/* Use emulation with fork. Rename pthread identifiers to avoid conflicts */

#include <sys/wait.h>

#define pthread_t				pg_pthread_t

error: patch failed: contrib/pgbench/pgbench.c:74
error: contrib/pgbench/pgbench.c: patch does not apply
Checking patch doc/src/sgml/pgbench.sgml...
error: while searching for:
     </varlistentry>

     <varlistentry>
      <term><option>-s</option> <replaceable>scale_factor</></term>
      <term><option>--scale=</option><replaceable>scale_factor</></term>
      <listitem>

error: patch failed: doc/src/sgml/pgbench.sgml:408
error: doc/src/sgml/pgbench.sgml: patch does not apply

For original context, see http://www.postgresql.org/message-id/alpine.DEB.2.02.1307110818260.11644@localhost6.localdomain6