Applied patch 1 of 1 for fwd-review-non-recursive-processing-of-and-or-lists
`git apply --verbose` output was:

```
Checking patch src/backend/parser/parse_expr.c...
error: while searching for:
static Node *
transformAExprAnd(ParseState *pstate, A_Expr *a)
{
	Node	   *lexpr = transformExprRecurse(pstate, a->lexpr);
	Node	   *rexpr = transformExprRecurse(pstate, a->rexpr);

	lexpr = coerce_to_boolean(pstate, lexpr, "AND");
	rexpr = coerce_to_boolean(pstate, rexpr, "AND");

	return (Node *) makeBoolExpr(AND_EXPR,
								 list_make2(lexpr, rexpr),
								 a->location);
}

static Node *
transformAExprOr(ParseState *pstate, A_Expr *a)
{
	Node	   *lexpr = transformExprRecurse(pstate, a->lexpr);
	Node	   *rexpr = transformExprRecurse(pstate, a->rexpr);

	lexpr = coerce_to_boolean(pstate, lexpr, "OR");
	rexpr = coerce_to_boolean(pstate, rexpr, "OR");

	return (Node *) makeBoolExpr(OR_EXPR,
								 list_make2(lexpr, rexpr),
								 a->location);
}

error: patch failed: src/backend/parser/parse_expr.c:920
error: src/backend/parser/parse_expr.c: patch does not apply
Checking patch src/test/regress/expected/rules.out...

```

For original context, see http://www.postgresql.org/message-id/CABwTF4VQALi23wqDwbxeM9+yMsArZ-tb=5yQK1s4y1P4QMZ7aA@mail.gmail.com